ALTER TABLE users ADD COLUMN IF NOT EXISTS elo INT NOT NULL DEFAULT 1200;
ALTER TABLE users ADD COLUMN IF NOT EXISTS peak_elo INT NOT NULL DEFAULT 1200;
ALTER TABLE users ADD COLUMN IF NOT EXISTS wins INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS losses INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_streak INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS best_streak INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_registered BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE games ADD COLUMN IF NOT EXISTS p1_elo_before INT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS p1_elo_after INT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS p2_elo_before INT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS p2_elo_after INT;

CREATE INDEX IF NOT EXISTS idx_users_elo ON users(elo DESC);
